version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
    labels:
      - "dependencies"
      - "github-actions"

  # Docker dependencies (if any)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "docker"
    ignore:
      # Ignore minor Docker version updates for LinuxServer.io baseimage
      - dependency-name: "ghcr.io/linuxserver/baseimage-alpine"
        update-types: ["version-update:semver-patch"]